version: '3'
services:
  postgresdb:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: navi2022
      POSTGRES_DB: sim
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build:
      context: .
    ports:
      - 80:80
    env_file:
      - ./.env
    depends_on:
      - postgresdb
volumes:
  postgres_data:
